---

- name:  
  shell: rm -rf /var/tmp/{{ deploy_dir }}

- name: Creates /var/tmp/directory
  file: path=/var/tmp/{{ deploy_dir }}  recurse=yes state=directory

- name: Copy kube config files
  template: src="{{ item.src }}" dest="/var/tmp/{{ deploy_dir }}/{{ item.dest }}"
  with_items:
    - { src: 'istio.yaml', dest: 'istio.yaml'  }
  register: result

- name:  
  shell: kubectl apply -f /var/tmp/{{ deploy_dir }}
  ignore_errors: True
  when: result|changed
