apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-volume-1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zk-storage # There is a built in provisioner for this class
  local:
    path: /tmp/zk # a folder under where the NFS storage is mounted
  nodeAffinity: # Node affinity is required for local storage
    required:
      nodeSelectorTerms:
      - matchExpressions: # Limit the hosts to hosts that have it setup, in my case all of them
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-volume-2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zk-storage # There is a built in provisioner for this class
  local:
    path: /tmp/zk # a folder under where the NFS storage is mounted
  nodeAffinity: # Node affinity is required for local storage
    required:
      nodeSelectorTerms:
      - matchExpressions: # Limit the hosts to hosts that have it setup, in my case all of them
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-volume-3
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zk-storage # There is a built in provisioner for this class
  local:
    path: /tmp/zk # a folder under where the NFS storage is mounted
  nodeAffinity: # Node affinity is required for local storage
    required:
      nodeSelectorTerms:
      - matchExpressions: # Limit the hosts to hosts that have it setup, in my case all of them
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node3
