---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: kiali
  namespace: istio-system
spec:
  rules:
  - host: kiali.10.0.15.10.nip.io
    http:
      paths:
      - backend:
          serviceName: kiali
          servicePort: 20001
        path: /

