apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
    version: v0.9.0
data:
  config.yaml: |
    server:
      port: 20001
      web_root: /
    external_services:
      jaeger:
        url: tracing.istio-system:80
      grafana:
        url: grafana.istio-system:3000
