---

- name: Creates /var/tmp/addon directory
  file: path=/var/tmp/analytics  recurse=yes state=directory

- name: Copy kube config files
  template: src="{{ item.src }}" dest="/var/tmp/analytics/{{ item.dest }}"
  with_items:
    - { src: 'pipeline.yml.j2', dest: 'pipeline.yml'  }
    - { src: 'pipeline-ingress.yml.j2', dest: 'pipeline-ingress.yml'  }
  register: result

- name:  
  shell: kubectl apply -n {{ namespace }} -f /var/tmp/analytics/{{ item }}
  with_items:
    - "pipeline.yml"
    - "pipeline-ingress.yml"
  ignore_errors: True
  when: result|changed
