---

- name: Creates /var/tmp/addon directory
  file: path=/var/tmp/analytics  recurse=yes state=directory

- name: Copy kube config files
  template: src="{{ item.src }}" dest="/var/tmp/analytics/{{ item.dest }}"
  with_items:
    - { src: 'hdfs-nn-storage-class.yaml.j2', dest: 'hdfs-nn-storage-class.yaml'  }
    - { src: 'hdfs-nn-storage.yaml.j2', dest: 'hdfs-nn-storage.yaml'  }
    #- { src: 'hdfs-core-site.yml.j2', dest: 'hdfs-core-site.yml'  }
    #- { src: 'hdfs-hdfs-site.yml.j2', dest: 'hdfs-hdfs-site.yml'  }
    - { src: 'hdfs-nn.yml.j2', dest: 'hdfs-nn.yml'  }
    - { src: 'hdfs-configMap.yaml.j2', dest: 'hdfs-configMap.yaml'  }
    - { src: 'hdfs-nn-ingress.yml.j2', dest: 'hdfs-nn-ingress.yml'  }
  register: result

- name:  
  shell: kubectl apply  -n {{ namespace }} -f /var/tmp/analytics/{{ item }}
  with_items:
    - "hdfs-nn-storage-class.yaml"
    - "hdfs-nn-storage.yaml"
    #- "hdfs-core-site.yml"
    #- "hdfs-hdfs-site.yml"
    - "hdfs-nn.yml"
    - "hdfs-configMap.yaml"
    - "hdfs-nn-ingress.yml"
  ignore_errors: True
  when: result|changed
