---


- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  apt:
    name: "{{ item }}"
    state: installed
    #update_cache: yes
  with_items:
    - docker-ce

- name: Add docker insecure parameter
  replace:
    backup: yes
    dest: /lib/systemd/system/docker.service
    regexp: '(^ExecStart=.*\D)$'
    replace: '\1 --insecure-registry dckreg:5000 --insecure-registry dckreg:5000'
  register: result
  notify: Start {{ role_name }}

- name: Ensure systemd is reloaded if docker.service has changed
  shell: systemctl daemon-reload
  when: result|changed
