---

- name: Copy rsyslog  file
  template: src=00-ignore-log.conf.j2 dest=/etc/rsyslog.d/00-ignore-log.conf
  notify: restart rsyslog

- name: Copy rsyslog  file
  template: src=mesos.conf dest=/etc/rsyslog.d/mesos.conf
  notify: restart rsyslog

- name: Copy 30-docker.conf
  template: src=30-docker.conf.j2 dest=/etc/rsyslog.d/30-docker.conf
  notify: restart rsyslog

- name: Copy 35-remote-logging.conf.j2
  template: src=35-remote-logging.conf.j2 dest=/etc/rsyslog.d/35-remote-logging.conf
  notify: restart rsyslog

- name: Copy cleanup_logfiles.sh.j2
  template: src=cleanup_logfiles.sh.j2  dest=/etc/cron.daily/cleanup_logfiles.sh mode=755

- name: Copy hourly_docker_cleanup.sh.j2
  template: src=hourly_docker_cleanup.sh.j2  dest=/etc/cron.hourly/hourly_docker_cleanup.sh mode=755

- name: Copy logrotate-docker-log.j2
  template: src=logrotate-docker-log.j2  dest=/etc/logrotate.d/logrotate-docker-log mode=755


- include: Debian.yml
  when: ansible_os_family == "Debian"
  name: Running Debian.yml

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  name: Running Redhat.yml

