---

- name: Creates /var/tmp/addon directory
  file: path=/var/tmp/analytics  recurse=yes state=directory

- name: Copy kube config files
  template: src="{{ item.src }}" dest="/var/tmp/analytics/{{ item.dest }}"
  with_items:
    - { src: 'zp-storage-class.yaml.j2', dest: 'zp-storage-class.yaml'  }
    - { src: 'zp-storage.yaml.j2', dest: 'zp-storage.yaml'  }
    - { src: 'zp-ingress.yml.j2', dest: 'zp-ingress.yml'  }
    - { src: 'zp.yml.j2', dest: 'zp.yml'  }
  register: result

- name:  
  shell: kubectl apply -n {{ namespace }} -f /var/tmp/analytics/{{ item }}
  with_items:
    - "zp-storage-class.yaml"
    - "zp-storage.yaml"
    - "zp-ingress.yml"
    - "zp.yml"
  ignore_errors: True
  when: result|changed
