---

- name: Creates /var/tmp/addon directory
  file: path=/var/tmp/analytics  recurse=yes state=directory

- name: Copy kube config files
  template: src="{{ item.src }}" dest="/var/tmp/analytics/{{ item.dest }}"
  with_items:
    - { src: 'kafka-storage-class.yaml.j2', dest: 'kafka-storage-class.yaml'  }
    - { src: 'kafka-storage.yaml.j2', dest: 'kafka-storage.yaml'  }
    #- { src: 'server.properties.template.yaml.j2', dest: 'server.properties.template.yaml'  }
    - { src: 'kafka.yaml.j2', dest: 'kafka.yaml'  }
  register: result

- name:  
  shell: kubectl apply  -n {{ namespace }} -f /var/tmp/analytics/{{ item }}
  with_items:
    - "kafka-storage-class.yaml"
    - "kafka-storage.yaml"
    #- "server.properties.template.yaml"
    - "kafka.yaml"
  ignore_errors: True
