---
- name: create ssl cert dir
  file: path={{ master_cert_dir }} state=directory
  register: master_ssl_dir

- name: copy openssl conf file to create certificate
  template: src="openssl.conf.j2" dest={{ master_cert_dir }}/openssl.conf
 
- name: create kubenetes certificates
  register: create_cert
  command: "{{ item }}" 
  args:
    creates: "{{ master_cert_dir }}/apiserver.pem"
  with_items:
    - "openssl genrsa -out {{ master_cert_dir }}/ca-key.pem 2048"
    - "openssl req -x509 -new -nodes -key {{ master_cert_dir }}/ca-key.pem -days {{ cert_days }} -out {{ master_cert_dir }}/ca.pem -subj '/CN=kube-ca'"
    - "openssl genrsa -out {{ master_cert_dir }}/admin-key.pem 2048"
    - "openssl req -new -key {{ master_cert_dir }}/admin-key.pem -out {{ master_cert_dir }}/admin.csr -subj '/CN=kube-admin'"
    - "openssl x509 -req -in {{ master_cert_dir }}/admin.csr -CA {{ master_cert_dir }}/ca.pem -CAkey {{ master_cert_dir }}/ca-key.pem -CAcreateserial -out {{ master_cert_dir }}/admin.pem -days {{ cert_days }}"
    - "openssl genrsa -out {{ master_cert_dir }}/apiserver-key.pem 2048"
    - "openssl req -new -key {{ master_cert_dir }}/apiserver-key.pem -out {{ master_cert_dir }}/apiserver.csr -subj '/CN=kube-apiserver' -config {{ master_cert_dir }}/openssl.conf" 
    - "openssl x509 -req -in {{ master_cert_dir }}/apiserver.csr -CA {{ master_cert_dir }}/ca.pem -CAkey {{ master_cert_dir }}/ca-key.pem -CAcreateserial -out {{ master_cert_dir }}/apiserver.pem -days {{ cert_days }} -extensions v3_req -extfile {{ master_cert_dir }}/openssl.conf"

