kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-operator-sb
rules:
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["clusterservicebrokers"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: redis-enterprise-operator
subjects:
- kind: ServiceAccount
  name: redis-enterprise-operator
  namespace: rr-demo
roleRef:
  kind: ClusterRole
  name: redis-enterprise-operator-sb
  apiGroup: rbac.authorization.k8s.io
