---

- name: Creates /var/tmp/addon directory
  file: path=/var/tmp/analytics  recurse=yes state=directory

- name: Copy kube config files
  template: src="{{ item.src }}" dest="/var/tmp/analytics/{{ item.dest }}"
  with_items:
    - { src: 'spark-sm-storage-class.yaml.j2', dest: 'spark-sm-storage-class.yaml'  }
    - { src: 'spark-sm-storage.yaml.j2', dest: 'spark-sm-storage.yaml'  }
    - { src: 'spark-configMap.yaml.j2', dest: 'spark-configMap.yaml'  }
    - { src: 'spark-master-ingress.yml.j2', dest: 'spark-master-ingress.yml'  }
    #- { src: 'spark-env.yml.j2', dest: 'spark-env.yml'  }
    - { src: 'spark-sm.yml.j2', dest: 'spark-sm.yml'  }
  register: result

- name:  
  shell: kubectl apply  -n {{ namespace }} -f /var/tmp/analytics/{{ item }}
  with_items:
    - "spark-sm-storage-class.yaml"
    - "spark-sm-storage.yaml"
    - "spark-configMap.yaml"
    #- "spark-env.yml"
    - "spark-master-ingress.yml"
    - "spark-sm.yml"
  ignore_errors: True
  when: result|changed
