apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: istio-system
spec:
  tls:
  - hosts:
    - grafana.{{ domain }}
    secretName: tls-secret
  rules:
  - host: grafana.{{ domain }}
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
        path: /
