apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
  name: servicegraph
  namespace: istio-system
spec:
  tls:
  - hosts:
    - servicegraph.{{ domain }}
    secretName: tls-secret
  rules:
  - host: servicegraph.{{ domain }}
    http:
      paths:
      - backend:
          serviceName: servicegraph
          servicePort: 8088
        path: / 
