apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
  name: tracing
  namespace: istio-system
spec:
  tls:
  - hosts:
    - tracing.{{ domain }}
    secretName: tls-secret
  rules:
  - host: tracing.{{ domain }}
    http:
      paths:
      - backend:
          serviceName: tracing
          servicePort: 80
        path: /
